version: "3.7"
services:
  game:
    build:
      context: .
      dockerfile: ./docker/game.Dockerfile
    container_name: game
    depends_on:
      - querymanager
    network_mode: host
    restart: unless-stopped

  loginserver:
    build:
      context: .
      dockerfile: ./docker/loginserver.Dockerfile
    container_name: loginserver
    depends_on:
      - mysql
    network_mode: host
    restart: unless-stopped

  querymanager:
    build:
      context: .
      dockerfile: ./docker/querymanager.Dockerfile
    container_name: querymanager
    depends_on:
      - mysql
    network_mode: host
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: realots
    network_mode: host
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ""
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data:
