version: "3.7"
services:
  game:
    build:
      context: .
      dockerfile: ./docker/Game.Dockerfile
    container_name: game
    ports:
      - 7171:7171
      - 7172:7172
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: realots
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ""
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data:
